
import streamlit as st
from PIL import Image
import io
import base64

st.set_page_config(page_title="Room Remodel AI", layout="centered")

st.title("🏠 AI Room Remodel Preview")
st.markdown("Upload a photo of a room and choose a new style to see a remodeled version generated by AI.")

# Image upload
uploaded_file = st.file_uploader("Upload a room photo", type=["jpg", "jpeg", "png"])

# Style selection
style = st.selectbox("Choose a remodel style", ["Scandinavian", "Industrial", "Luxury", "Coastal", "Modern", "Minimalist"])

# Placeholder for image display
if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Original Room", use_column_width=True)

    st.markdown("Click below to generate a remodeled version in your selected style.")

    if st.button("✨ Remodel My Room"):
        # Fake output for demo – replace this section with real AI image generation
        st.success(f"Room remodeled in {style} style (demo preview).")

        st.markdown("Here's what a remodeled version *could* look like:")
        st.image(image.transpose(Image.FLIP_LEFT_RIGHT), caption=f"{style} Style Preview (Simulated)", use_column_width=True)
else:
    st.info("Please upload a room image to begin.")
